### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by zolotov** [liias/monkey#9]
```
2017-12-06 14:02:58,539 [   2951]  ERROR - oncurrency.BoundedTaskExecutor - class with name 'io.github.liias.monkey.runnoevil.MonkeyGenerateTestSupportMethodAction' cannot be loaded [Plugin: io.github.liias.monkey] 
com.intellij.diagnostic.PluginException: class with name 'io.github.liias.monkey.runnoevil.MonkeyGenerateTestSupportMethodAction' cannot be loaded [Plugin: io.github.liias.monkey]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.error(ActionManagerImpl.java:194)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:159)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:486)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:474)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1244)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:32)
	at com.intellij.openapi.application.Preloader.lambda$null$0(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.Preloader.lambda$initComponent$1(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/intellij/testIntegration/BaseGenerateTestSupportMethodAction
	at io.github.liias.monkey.runnoevil.MonkeyGenerateTestSupportMethodAction.<clinit>(MonkeyGenerateTestSupportMethodAction.java:24)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:152)
	... 15 more
Caused by: java.lang.ClassNotFoundException: com.intellij.testIntegration.BaseGenerateTestSupportMethodAction PluginClassLoader[io.github.liias.monkey, 0.3.5] com.intellij.ide.plugins.cl.PluginClassLoader@5ca6ec0
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
```

**Comment by liias** [comment]
Thanks for reporting. Will take a look in a few days.
